version: '1.0'

services:
  frontend:
    build: .
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ${PWD}:/app
    depends_on:
      - api
  api:
    build: ./server
    restart: always
    ports:
      - '5555:5000'
    volumes:
      - ${PWD}/server:/app
